# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: OS and Browser Combination Tests

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_and_test:
    name: ${{ matrix.os }} (${{ matrix.browser }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        browser: ['chromium', 'firefox', 'webkit']
        os: [ ubuntu-latest, macos-10.15, macos-11.0, windows-latest ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: 'npm'
    - run: npm ci
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    - run: npx playwright install --with-deps ${{ matrix.browser }}
    - run: npm run build --if-present
    - run: npm test
      env:
        BROWSER: ${{ matrix.browser }}
