# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Ubuntu Browser Test

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ['chromium', 'firefox', 'webkit']

    steps:
    - uses: actions/checkout@v2
    - name: Use Browser ${{ matrix.browser }}
      uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: 'npm'
    - run: npm ci
    - run: npx playwright install-deps
    - run: npm run build --if-present
    - run: npm test
      env:
        BROWSER: ${{ matrix.browser }}
